[package]
name = "is_dao_worthy"
type = "bin"
compiler_version = ">=0.26.0"

[dependencies]
ethereum_history_api = { path = "../../../../ethereum_history_api/circuits/lib" }
token = { path = "../lib" }
