[package]
name = "is_crypto_punk_owner"
type = "bin"
compiler_version = ">=0.31.0"

[dependencies]
ethereum = { path = "../../../../ethereum/circuits/lib" }
token = { path = "../../../ethereum/circuits/lib" }
