[package]
name = "noir_ethereum_history_api"
type = "bin"
authors = ["Arkadiusz Konior, Marek Kirejczyk"]
compiler_version = "0.22.0"

[dependencies]
proof = { path = "./deps/noir-trie-proofs/lib/" }
