address = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
block_no = ""
state_root = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
