name: Circuits E2E Tests

on: [push]

jobs:
  test:
    name: Circuits E2E Tests
    runs-on: 32-core-ubuntu-runner
    environment: CI
    env:
      ETHEREUM_JSON_RPC_API_URL: ${{ secrets.ETHEREUM_JSON_RPC_API_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Enable Corepack and Install Yarn 4
        run: |
          corepack enable
          yarn set version latest

      - name: Install Dependencies
        run: yarn install

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: 0.26.0

      - name: Compile Circuit
        run: nargo compile --workspace

      - name: Start Oracle Server
        working-directory: ethereum_history_api/oracles
        run: |
          yarn oracle-server &
          ORACLE_SERVER_PID=$!
          echo "ORACLE_SERVER_PID=$ORACLE_SERVER_PID" >> $GITHUB_ENV

      - name: Generate Proof
        run: |
          nargo prove --package get_header --oracle-resolver=http://localhost:5555
          nargo prove --package get_account --oracle-resolver=http://localhost:5555
          nargo prove --package get_storage --oracle-resolver=http://localhost:5555
          nargo prove --package get_receipt --oracle-resolver=http://localhost:5555
          nargo prove --package is_dao_worthy --oracle-resolver=http://localhost:5555

      - name: Verify Proof
        run: |
          nargo verify --package get_header
          nargo verify --package get_account
          nargo verify --package get_storage
          nargo verify --package get_receipt
          nargo verify --package is_dao_worthy

      - name: Stop Oracle Server
        if: always()
        run: kill $ORACLE_SERVER_PID
      
      - name: Archive is_dao_worthy proof
        uses: actions/upload-artifact@v4
        with:
          name: proof of is_dao_worthy
          path: proofs/is_dao_worthy.proof
