name: circuit tests

on: [push]

jobs:
  test:
    name: nargo test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: nightly # Pin at 0.23.0 when it's released. We need nightly now as 0.22.0 doesn't have the oracles
      - name: Run nargo test
        run: |
          cd circuit
          nargo test
