name: ethereum_history_api contract tests

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: 32-core-ubuntu-runner
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: 0.29.0

      - name: Run nargo codegen-verifier
        run: |
          nargo codegen-verifier --package get_storage
          nargo codegen-verifier --package get_account
          nargo codegen-verifier --package get_header
          nargo codegen-verifier --package get_receipt
          nargo codegen-verifier --package get_transaction

      - name: Run Forge build
        run: |
          cd ethereum_history_api/contracts
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd ethereum_history_api/contracts
          forge test -vvv
        id: test
