name: TS Lint and Typecheck

on: [push]

jobs:
  lint-and-typecheck:
    name: Lint and Typecheck
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Enable Corepack and Install Yarn 4
        run: |
          corepack enable
          yarn set version latest

      - name: Install Dependencies
        run: yarn install

      # We don't store circuit and smart contract compilation artefacts in the repo,
      # but typecheck fails on import without them so we just create fake files here
      - name: Create fake circuit compilation artefacts
        working-directory: .
        run: |
          mkdir -p target
          echo '{ "abi": [] }' > target/get_storage.json
          echo '{ "abi": [] }' > target/get_account.json
          echo '{ "abi": [] }' > target/get_header.json

      - name: Create fake smart contract build artefacts
        working-directory: .
        run: |
          mkdir -p ethereum_history_api/contracts/out/GetStorageUltraPLONKVerifier.sol
          echo '{ "abi": [], "bytecode": { "object": "" } }' > ethereum_history_api/contracts/out/GetStorageUltraPLONKVerifier.sol/UltraVerifier.json
          mkdir -p ethereum_history_api/contracts/out/GetAccountUltraPLONKVerifier.sol
          echo '{ "abi": [], "bytecode": { "object": "" } }' > ethereum_history_api/contracts/out/GetAccountUltraPLONKVerifier.sol/UltraVerifier.json
          mkdir -p ethereum_history_api/contracts/out/GetHeaderUltraPLONKVerifier.sol
          echo '{ "abi": [], "bytecode": { "object": "" } }' > ethereum_history_api/contracts/out/GetHeaderUltraPLONKVerifier.sol/UltraVerifier.json

      - name: Run TypeScript Build
        run: yarn build

      - name: Run TypeScript format check
        run: yarn format:all:ci

      # It's important to run lint after build as eslint does not support project references yet
      # https://github.com/typescript-eslint/typescript-eslint/issues/2094
      - name: Run TypeScript Linter
        run: yarn lint:all
