name: TS tests

on: [push]

jobs:
  test:
    name: yarn test
    runs-on: ubuntu-latest
    environment: CI
    env:
      ETHEREUM_JSON_RPC_API_URL: ${{ secrets.ETHEREUM_JSON_RPC_API_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: nightly-2024-01-11 # Pin at 0.23.0 when it's released. We need nightly now as 0.22.0 doesn't have the oracles

      - name: Compile Circuit
        run: nargo compile
        working-directory: circuit

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Enable Corepack and Install Yarn 4
        run: |
          corepack enable
          yarn set version latest

      - name: Install Dependencies
        run: yarn install
        working-directory: packages/noir-ethereum-api

      - name: Run Tests
        run: yarn test
        working-directory: packages/noir-ethereum-api
