name: TS tests

on: [push]

jobs:
  test:
    name: yarn test
    runs-on: 32-core-ubuntu-runner
    environment: CI
    env:
      ETHEREUM_JSON_RPC_API_URL: ${{ secrets.ETHEREUM_JSON_RPC_API_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Enable Corepack and Install Yarn 4
        run: |
          corepack enable
          yarn set version latest

      - name: Install Dependencies
        run: yarn install

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: 0.23.0

      - name: Compile Circuit
        run: nargo compile --workspace

      - name: Start Oracle Server
        working-directory: ethereum_history_api/oracles
        run: |
          yarn oracle-server &
          ORACLE_SERVER_PID=$!
          echo "ORACLE_SERVER_PID=$ORACLE_SERVER_PID" >> $GITHUB_ENV

      - name: Generate Proof
        run: |
          nargo prove --package get_header --oracle-resolver=http://localhost:5555
          nargo prove --package get_account --oracle-resolver=http://localhost:5555

      - name: Veirfy Proof
        run: nargo verify --package get_account

      - name: Run nargo codegen-verifier
        run: |
          nargo codegen-verifier --package get_header
          nargo codegen-verifier --package get_account

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Compile Smart Contract
        working-directory: ethereum_history_api/contracts
        run: forge build

      - name: Run TypeScript Build
        run: yarn build

      - name: Run Unit Tests
        working-directory: ethereum_history_api/oracles
        run: yarn test:unit

      - name: Run e2e Tests
        working-directory: ethereum_history_api/tests
        run: yarn test:e2e

      - name: Stop Oracle Server
        if: always()
        run: kill $ORACLE_SERVER_PID
