name: yarn tests

on: [push]

jobs:
  test:
    name: yarn test
    runs-on: ubuntu-latest
    environment: CI
    env:
      ETHEREUM_JSON_RPC_API_URL: ${{ secrets.ETHEREUM_JSON_RPC_API_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install yarn 4
        run: |
          corepack enable
          yarn set version latest
      - name: Install depdendencies
        run: |
          cd packages/ethereum
          yarn install

      - name: Run tests
        run: |
          cd packages/ethereum
          yarn test
